### Créer une article

POST http://localhost:8080/articles
Content-Type: application/json

{
"nom": "Dupont Jean",
"email": "dupont&dupont@mail.com"
}

### Lister toutes les articles

GET http://localhost:8080/articles

### Récupérer une article par ID (exemple avec id=1)

GET http://localhost:8080/articles/2

### Modifier une article (exemple avec id=1)

PUT http://localhost:8080/articles/22
Content-Type: application/json

{
"nom": "Durand Paul",
"email": "pololejardinier@mail.com"
}

### Supprimer une article (exemple avec id=1)

DELETE http://localhost:8080/articles/1
